// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKeBpWH6sCFXv6pVtZVheh_fr-aGjDInw',
    appId: '1:152809500647:web:a965c8c9e96b480e5d5742',
    messagingSenderId: '152809500647',
    projectId: 'test-1705a',
    authDomain: 'test-1705a.firebaseapp.com',
    storageBucket: 'test-1705a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCatNbTljG9NHn0Vhw4UojiDe6_3N6ml2Y',
    appId: '1:152809500647:android:95c36f7ffe52e7d55d5742',
    messagingSenderId: '152809500647',
    projectId: 'test-1705a',
    storageBucket: 'test-1705a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBsFFcv9_umqPokzAfQl2vHvxo6ENnpaw',
    appId: '1:152809500647:ios:6d2999eba3851f255d5742',
    messagingSenderId: '152809500647',
    projectId: 'test-1705a',
    storageBucket: 'test-1705a.appspot.com',
    iosBundleId: 'com.example.test2',
  );
}
